name: Publish on Release

on:
  release:
    branches:
      - master
      - 5.x
    types: [published]

jobs:
  run-publishing:
    uses: ./.github/workflows/publish.yml
    with:
      prerelease: ${{ github.event.release.prerelease }}
    secrets: inherit
